/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.lang.Math;
import java.util.Date;

public class _block__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;

  
  	String signBomb="\u9032\u5165\u6a19\u8a18\u6a21\u5f0f";
  	String time="";													//\u6642\u9593
  	boolean bottonDif[][]=new boolean[9][9];						//\u6309\u9215\u662f\u5426\u70ba""\u4e14\u5df2\u88ab\u64f4\u6563
  	String btn[][]=new String[9][9];								//\u6309\u9215 name
  	String bottonSet[][]=new String[9][9];							//\u6309\u9215\u7f8e\u7de8(\u662f\u5426\u986f\u793a)
  	String hiddenSet="font-size:999px;background-color:#cbadea; class=\"blockHidden\"";	//\u7f8e\u7de8\u70ba\u96b1\u85cf
  	String clearSet="font-size:20px;background-color:#F9F9F9;";		//\u7f8e\u7de8\u70ba\u986f\u793a
  	boolean welcome=true;											//\u662f\u5426\u7b2c\u4e00\u6b21\u9032\u6b64\u9801\u9762
  	String botton[][]=new String[9][9]; 							//\u6309\u9215\u672c\u8eab
  	
  	public void setMap(){
  		/*\u521d\u59cb\u5316\u6642\u9593\u53ca\u6a19\u8a18\u6a21\u5f0f*/
  		Date date = new Date();
  		time=date.toString();
  		signBomb="\u9032\u5165\u6a19\u8a18\u6a21\u5f0f";
  		/*\u521d\u59cb\u5316\u6309\u9215*/
  		for(int i=0;i<=8;i++){
  			for(int j=0;j<=8;j++){
  				botton[i][j]="";
  				btn[i][j]="["+Integer.toString(i)+"]"+"["+Integer.toString(j)+"]";
  				bottonSet[i][j]=hiddenSet;
  				bottonDif[i][j]=false;
  			}
  		}
  		/*\u4e82\u6578\u8a2d\u5b9a\u70b8\u5f48\u5ea7\u6a19*/
  		int count=0;
  		while(count!=10){
  			int x=(int)(Math.random()*9),y=(int)(Math.random()*9); 
  			if(!botton[x][y].equals("*")){
  				botton[x][y]="*";
  				count++;
  			}
  		}
  		/*\u5275\u5efa\u5730\u5716\u6578\u5b57*/
  		for(int x=0;x<=8;x++){
  			for(int y=0;y<=8;y++){
  				if(!botton[x][y].equals("*")){
  					count=0;
  					if(y+1<=8 && botton[x][y+1].equals("*"))count++;
  					if(y-1>=0 && botton[x][y-1].equals("*"))count++;
  					if(x-1>=0 && botton[x-1][y].equals("*"))count++;
  					if(x+1<=8 && botton[x+1][y].equals("*"))count++;
  					if(x-1>=0 && y+1<=8 && botton[x-1][y+1].equals("*"))count++;
  					if(x-1>=0 && y-1>=0 && botton[x-1][y-1].equals("*"))count++;
  					if(x+1<=8 && y-1>=0 && botton[x+1][y-1].equals("*"))count++;
  					if(x+1<=8 && y+1<=8 && botton[x+1][y+1].equals("*"))count++;
  					if(count!=0)botton[x][y]=Integer.toString(count);
  				}
  			}
  		}
  
  	}
  	public void diffusion(int x,int y){
  		/*\u4e5d\u5bae\u683c\u905e\u8ff4\u64f4\u6563*/
  		bottonDif[x][y]=true;
  		if(y+1<=8) {
  			bottonSet[x][y+1]=clearSet;
  			if(botton[x][y+1].equals("")&&!bottonDif[x][y+1])diffusion(x,y+1);
  		}if(y-1>=0) {
  			bottonSet[x][y-1]=clearSet;
  			if(botton[x][y-1].equals("")&&!bottonDif[x][y-1])diffusion(x,y-1);
  		}if(x-1>=0) {
  			bottonSet[x-1][y]=clearSet;
  			if(botton[x-1][y].equals("")&&!bottonDif[x-1][y])diffusion(x-1,y);
  		}if(x+1<=8) {
  			bottonSet[x+1][y]=clearSet;
  			if(botton[x+1][y].equals("")&&!bottonDif[x+1][y])diffusion(x+1,y);
  		}if(x-1>=0 && y+1<=8) {
  			bottonSet[x-1][y+1]=clearSet;
  			if(botton[x-1][y+1].equals("")&&!bottonDif[x-1][y+1])diffusion(x-1,y+1);
  		}if(x-1>=0 && y-1>=0) {
  			bottonSet[x-1][y-1]=clearSet;
  			if(botton[x-1][y-1].equals("")&&!bottonDif[x-1][y-1])diffusion(x-1,y-1);
  		}if(x+1<=8 && y-1>=0) {
  			bottonSet[x+1][y-1]=clearSet;
  			if(botton[x+1][y-1].equals("")&&!bottonDif[x+1][y-1])diffusion(x+1,y-1);
  		}if(x+1<=8 && y+1<=8) {
  			bottonSet[x+1][y+1]=clearSet;
  			if(botton[x+1][y+1].equals("")&&!bottonDif[x+1][y+1])diffusion(x+1,y+1);
  		}
  	}
  	/*\u662f\u5426\u7b26\u5408\u52dd\u5229\u689d\u4ef6*/
  	public boolean win(){
  		for(int x=0;x<=8;x++){
  			for(int y=0;y<=8;y++){
  				if(!botton[x][y].equals("*") && bottonSet[x][y].equals(hiddenSet))return false;
  			}
  		}return true;
  	}
  	public void sign(){
  		if(bottonSet[0][0].equals(hiddenSet)){
  			bottonSet[0][0]=hiddenSet+"background-image: url(\"sign.png\")";
  		}else bottonSet[0][0]=hiddenSet;
  	}

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=Big5");
    request.setCharacterEncoding("Big5");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	
	/*\u904a\u6232\u958b\u59cb\uff0c\u96a8\u6a5f\u9810\u8a2d\u5730\u5716*/
	if(request.getParameter("start") != null||request.getParameter("reset")!=null){
		welcome=true;
	}
	if(welcome){
		setMap();
		session.setAttribute("time",time);
		welcome=false;
	}
	if(request.getParameter("sign")!=null){
		if(signBomb.equals("\u9032\u5165\u6a19\u8a18\u6a21\u5f0f"))signBomb="\u53d6\u6d88\u6a19\u8a18\u6a21\u5f0f";
		else signBomb="\u9032\u5165\u6a19\u8a18\u6a21\u5f0f";
	}
	/*\u6309\u9215\u5075\u6e2c*/
	if(signBomb.equals("\u9032\u5165\u6a19\u8a18\u6a21\u5f0f")){
		for(int x=0;x<=8;x++){
			for(int y=0;y<=8;y++){
				if(request.getParameter(btn[x][y]) != null){//\u5982\u679c\u6709\u6309\u9215\u88ab\u6309\u4e0b\u5c31\u9032\u5165\u5075\u6e2c
					if(request.getParameter(btn[x][y]).equals("*")) {//\u7206\u70b8
						for(int i=0;i<=8;i++){
							for(int j=0;j<=8;j++){
								session.setAttribute("botton"+"["+Integer.toString(i)+"]["+Integer.toString(j)+"]"
								,botton[i][j]);
								session.setAttribute("bottonSet"+"["+Integer.toString(i)+"]["+Integer.toString(j)+"]"
								,bottonSet[i][j]);
							}
						}
      pageContext.forward("over.jsp");
      if (true) return;
      
					}else{	//\u6c92\u7206\u70b8
						bottonSet[x][y]=clearSet;
						if(botton[x][y].equals("")){
							diffusion(x,y);
						}if(win()){
							session.setAttribute("win","true");
							for(int i=0;i<=8;i++){
								for(int j=0;j<=8;j++){
									session.setAttribute("botton"+"["+Integer.toString(i)+"]["+Integer.toString(j)+"]"
									,botton[i][j]);
									session.setAttribute("bottonSet"+"["+Integer.toString(i)+"]["+Integer.toString(j)+"]"
									,bottonSet[i][j]);
								}
							}
      pageContext.forward("over.jsp");
      if (true) return;
      
						} 
					}
				}
			}
		}	
	}else{/*\u6a19\u8a18\u6a21\u5f0f*/
		for(int x=0;x<=8;x++){
			for(int y=0;y<=8;y++){
				if(request.getParameter(btn[x][y]) != null){//\u5982\u679c\u6709\u6309\u9215\u88ab\u6309\u4e0b\u5c31\u9032\u5165\u5075\u6e2c
					if(bottonSet[x][y].equals(hiddenSet))bottonSet[x][y]="background-image:url(\"sign1.png\");"+hiddenSet;
					else if(bottonSet[x][y].equals("background-image:url(\"sign1.png\");"+hiddenSet))bottonSet[x][y]=hiddenSet;
				}
			}
		}	
	}
	
	

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((signBomb));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((bottonSet[0][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[0][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[0][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[0][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[0][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[0][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[0][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[0][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[0][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[0][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[0][8]));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((bottonSet[1][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[1][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[1][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[1][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[1][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[1][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[1][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[1][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[1][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[1][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[1][8]));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((bottonSet[2][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[2][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[2][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[2][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[2][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[2][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[2][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[2][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[2][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[2][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[2][8]));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((bottonSet[3][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[3][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[3][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[3][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[3][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[3][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[3][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[3][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[3][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[3][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[3][8]));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((bottonSet[4][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[4][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[4][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[4][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[4][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[4][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[4][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[4][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[4][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[4][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[4][8]));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((bottonSet[5][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[5][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[5][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[5][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[5][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[5][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[5][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[5][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[5][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[5][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[5][8]));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((bottonSet[6][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[6][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[6][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[6][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[6][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[6][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[6][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[6][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[6][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[6][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[6][8]));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((bottonSet[7][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[7][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[7][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[7][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[7][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[7][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[7][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[7][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[7][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[7][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[7][8]));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((bottonSet[8][0]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][0]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][0]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[8][1]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][1]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][1]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[8][2]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][2]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][2]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[8][3]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][3]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][3]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[8][4]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][4]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][4]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[8][5]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][5]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][5]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[8][6]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][6]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][6]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[8][7]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][7]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][7]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((bottonSet[8][8]));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((btn[8][8]));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((botton[8][8]));
      out.write(_jsp_string7, 0, _jsp_string7.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("block.jsp"), 7835285614900309930L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  static {
    _jsp_string5 = " >\r\n			</td>\r\n			<td align='center' valign=\"middle\">\r\n				<input style=".toCharArray();
    _jsp_string6 = " >\r\n			</td>\r\n		</tr>\r\n		<tr>\r\n			<td align='center' valign=\"middle\">\r\n				<input style=".toCharArray();
    _jsp_string3 = " type=\"submit\" name=".toCharArray();
    _jsp_string7 = " >\r\n			</td>\r\n		</tr>\r\n	</table>\r\n</form>\r\n</BODY>\r\n</HTML>\r\n".toCharArray();
    _jsp_string2 = " >\r\n		<FONT SIZE = 5 style=\"color:rgb(26, 60, 64) ;\"><b>\u8e29\u5730\u96f7\u904a\u6232</b></FONT>\r\n		<input style= \"height:25px;width:50px;font-size:20px; font-size: 15px;\" \r\n		class=\"btn\" type=\"submit\" name=\"reset\" value=\"\u91cd\u958b\" >\r\n	</form>\r\n</CENTER>\r\n\r\n\r\n<form action=\"block.jsp\" method=post name=form>\r\n	<table style=\"border-collapse: collapse;border-spacing: 0;\" align=\"center\" bgcolor=\"FFECEC\" border=\"0\">\r\n		<tr>\r\n			<td align='center' valign=\"middle\">\r\n				<input style=".toCharArray();
    _jsp_string1 = "\r\n<style>\r\n	input{\r\n		height:70px;\r\n		width:70px;\r\n	}\r\n	.btn{\r\n        transition:0.3s;\r\n		background-color:F9F9F9;\r\n    }\r\n    .btn:hover{\r\n        opacity:1.5;\r\n		background-color:B3E8E5;\r\n    }\r\n	.btn:active{\r\n    background-color: FFC3C3;\r\n    }\r\n	.blockHidden{\r\n		transition:0.3s;\r\n		font-size:20px;\r\n		background-color:#F9F9F9;\r\n	}\r\n	.blockHidden:hover{\r\n		box-shadow:inset 0 0 0 3px #816797;\r\n	}\r\n	.blockShow{\r\n		font-size:999px;\r\n		background-color:#cbadea;\r\n	}\r\n</style>\r\n\r\n<CENTER>\r\n	<form action=\"block.jsp\" method=post name=form1>\r\n		<input style= \"height:25px;width:120px;font-size:20px; font-size: 15px;\" \r\n		class=\"btn\" type=\"submit\" name=\"sign\" value=".toCharArray();
    _jsp_string4 = " value=".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!--\r\n	\u7db2\u8def\u7a0b\u5f0f\u8a2d\u8a08\u5c08\u984c\u5831\u544a\uff0c\u7d44\u54e1\uff1a\u6c5f\u82f1\u78a9\u3001\u90ed\u9038\u51e1\r\n\r\n	\u524d\u8a00\uff1a\u9019\u500b\u7a0b\u5f0f\u78bc\u4e26\u6c92\u6709\u53c3\u8003\u7db2\u8def\u4e0a\u7684\u7a0b\u5f0f\uff0c\u5168\u90e8\u81ea\u5df1\u5f9e\u982d\u7de8\u5beb\uff0c\u4f46\u4e5f\u56e0\u6b64\u8aa4\u628a\u8b8a\u6578\u540d\u7a31button\u62fc\u932f\r\n	\u6210botton\u4f46\u662f\u985e\u4f3c\u7684\u8b8a\u6578\u540d\u7a31\u592a\u591a\uff0c\u6545\u6c92\u6709\u53bb\u4e00\u4e00\u4fee\u6539\uff0c\u6709\u6642\u9593\u7684\u8a71\u4e00\u5b9a\u6539\u6b63\r\n\r\n	\u4f7f\u7528\u8aaa\u660e\uff1a\r\n-->\r\n<HTML>\r\n<HEAD>\r\n<TITLE>\u8e29\u5730\u96f7</TITLE>\r\n</HEAD>\r\n\r\n<BODY bgcolor=\"#b6fcf1\">\r\n	\r\n\r\n\r\n".toCharArray();
  }
}
