/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _error__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, null, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    java.lang.Throwable exception = ((com.caucho.jsp.PageContextImpl) pageContext).getThrowable();
    response.setContentType("text/html;charset=Big5");
    request.setCharacterEncoding("Big5");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("error.jsp"), 3647329954176466133L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n\r\n<HTML>\r\n<HEAD>\r\n<TITLE>\u8e29\u5730\u96f7\u932f\u8aa4\u756b\u9762</TITLE>\r\n<style>\r\n    #middle{\r\n	position: absolute;\r\n    top:50%;\r\n    left:50%;\r\n    transform:translateX(-50%) translateY(-50%);\r\n    }\r\n    .box{\r\n    width: 200px;\r\n    height: 200px;\r\n    background: #ecd6c7;\r\n    margin: 0 auto;/*\u5340\u584a\u7f6e\u4e2d*/\r\n    }\r\n    #bottom{\r\n    position: absolute;\r\n	width: 100%;\r\n	height: 50px;\r\n	bottom: 0px;\r\n    text-align: center;\r\n    margin: 0px;\r\n    background-color:#1c2222;\r\n    }\r\n    .btn{\r\n        opacity: 0.8;\r\n        transition:0.3s;\r\n    }\r\n    .btn:hover{\r\n        opacity:1;\r\n        transform:scale(1.2);\r\n    }\r\n</style>\r\n</HEAD>\r\n<BODY bgcolor=\"#b6fcf1\" style=\"margin:0px;\">\r\n\r\n\r\n    <div id=\"middle\">\r\n        <img style=\"display:block; margin:auto;\" width=50% src=\"mine.png\" alt=\"mine\">\r\n        <h1 style=\"color: #1B2430;text-align:center;\">\u4f7f\u7528\u4e0d\u7576\u51fa\u73fe\u932f\u8aa4\uff0c\u6309\u4e0bstart\u91cd\u65b0\u958b\u59cb\uff01</h1>\r\n        <FORM action=\"block.jsp\" method=post name=FORM>\r\n            <table align=\"center\" bgcolor=\"FFECEC\" border=\"0\">\r\n                <tr>\r\n                    <td align='center' valign=\"middle\">\r\n                        <input class=\"btn\" style= \"background-color:F9F9F9;height:50px;width:70px;font-size:20px;\" \r\n                        type=\"submit\" name=\"start\" value=\"start\" >\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n        </FROM>\r\n    </div>\r\n    <div id=\"bottom\">\r\n        <p style=\"color:rgb(124, 209, 184)\">\u7db2\u8def\u7a0b\u5f0f\u8a2d\u8a08\u5c08\u984c   \u7d44\u54e1:\u6c5f\u82f1\u78a9 \u90ed\u9038\u51e1</p>\r\n    </div>\r\n</BODY>\r\n</HTML>".toCharArray();
  }
}
